const data = [
  {
    id: "recZkNf2kwmdBcqd0",
    name: "Green Top",
    price: 25,
    image: "",
    company: "Levis",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recEHmzvupvT8ZONH",
    name: "Floral Top",
    price: 60,
    image: "",
    company: "Vero Moda",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 6,
  },
  {
    id: "rec5NBwZ5zCD9nfF0",
    name: "Floral Dress",
    price: 50,
    image: "",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    amount: 1,
    stock: 4,
  },
  {
    id: "recd1jIVIEChmiwhe",
    name: "Red Dress",
    price: 70,
    image: "",
    company: "Vero Moda",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recoM2MyHJGHLVi5l",
    name: "Striped Sweater",
    price: 80,
    image: "",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recotY5Nh00DQFdkm",
    name: "Yellow Trouser",
    price: 20,
    image: "",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "rec1Ntk7siEEW9ha1",
    name: "White Top",
    price: 40,
    image: "",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 2,
  },
  {
    id: "recNZ0koOqEmilmoz",
    name: "Pink Sweatshirt",
    price: 90,
    image: "",
    company: "Levis",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 3,
  },
  {
    id: "recrfxv3EwpvJwvjq",
    name: "Brown Coat",
    price: 100,
    image: "",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recoW8ecgjtKx2Sj2",
    name: "Grey Jacket",
    price: 20,
    image: "",
    company: "Vero Moda",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    amount: 1,
    stock: 5,
  },
];
export default data;
